# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20200402_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
