# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coustomerrecord',
            options={'ordering': ['-id'], 'verbose_name': '客户跟进表', 'verbose_name_plural': '客户跟进表'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': '客户信息表', 'verbose_name_plural': '客户信息表'},
        ),
        migrations.AddField(
            model_name='customer',
            name='remark',
            field=models.TextField(default='无', verbose_name='备注...'),
        ),
    ]
